# Code generated by fin-protoc. DO NOT EDIT.
from bytebuf import ByteBuf
from codec import *

class NewOrderSingle(BinaryCodec):
    def __init__(self):
        self.biz_id = 0
        self.biz_pbu = ''
        self.cl_ord_id = ''
        self.security_id = ''
        self.account = ''
        self.owner_type = 0
        self.side = ''
        self.price = 0
        self.order_qty = 0
        self.ord_type = ''
        self.time_in_force = ''
        self.transact_time = 0
        self.credit_tag = ''
        self.clearing_firm = ''
        self.branch_id = ''
        self.user_info = ''
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u32(self.biz_id)
        write_fixed_string(buffer, self.biz_pbu, 8)
        write_fixed_string(buffer, self.cl_ord_id, 10)
        write_fixed_string(buffer, self.security_id, 12)
        write_fixed_string(buffer, self.account, 13)
        buffer.write_u8(self.owner_type)
        write_fixed_string(buffer, self.side, 1)
        buffer.write_i64(self.price)
        buffer.write_i64(self.order_qty)
        write_fixed_string(buffer, self.ord_type, 1)
        write_fixed_string(buffer, self.time_in_force, 1)
        buffer.write_u64(self.transact_time)
        write_fixed_string(buffer, self.credit_tag, 2)
        write_fixed_string(buffer, self.clearing_firm, 8)
        write_fixed_string(buffer, self.branch_id, 8)
        write_fixed_string(buffer, self.user_info, 32)
    
    def decode(self, buffer: ByteBuf):
        self.biz_id = buffer.read_u32()
        self.biz_pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.security_id = buffer.read_bytes(12).decode('utf-8').strip('\x00')
        self.account = buffer.read_bytes(13).decode('utf-8').strip('\x00')
        self.owner_type = buffer.read_u8()
        self.side = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.price = buffer.read_i64()
        self.order_qty = buffer.read_i64()
        self.ord_type = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.time_in_force = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.transact_time = buffer.read_u64()
        self.credit_tag = buffer.read_bytes(2).decode('utf-8').strip('\x00')
        self.clearing_firm = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.branch_id = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.user_info = buffer.read_bytes(32).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.biz_id == other.biz_id,
            self.biz_pbu == other.biz_pbu,
            self.cl_ord_id == other.cl_ord_id,
            self.security_id == other.security_id,
            self.account == other.account,
            self.owner_type == other.owner_type,
            self.side == other.side,
            self.price == other.price,
            self.order_qty == other.order_qty,
            self.ord_type == other.ord_type,
            self.time_in_force == other.time_in_force,
            self.transact_time == other.transact_time,
            self.credit_tag == other.credit_tag,
            self.clearing_firm == other.clearing_firm,
            self.branch_id == other.branch_id,
            self.user_info == other.user_info
        ])
        
    


class OrderReject(BinaryCodec):
    def __init__(self):
        self.biz_id = 0
        self.biz_pbu = ''
        self.cl_ord_id = ''
        self.security_id = ''
        self.ord_rej_reason = 0
        self.trade_date = 0
        self.transact_time = 0
        self.user_info = ''
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u32(self.biz_id)
        write_fixed_string(buffer, self.biz_pbu, 8)
        write_fixed_string(buffer, self.cl_ord_id, 10)
        write_fixed_string(buffer, self.security_id, 12)
        buffer.write_u32(self.ord_rej_reason)
        buffer.write_u32(self.trade_date)
        buffer.write_u64(self.transact_time)
        write_fixed_string(buffer, self.user_info, 32)
    
    def decode(self, buffer: ByteBuf):
        self.biz_id = buffer.read_u32()
        self.biz_pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.security_id = buffer.read_bytes(12).decode('utf-8').strip('\x00')
        self.ord_rej_reason = buffer.read_u32()
        self.trade_date = buffer.read_u32()
        self.transact_time = buffer.read_u64()
        self.user_info = buffer.read_bytes(32).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.biz_id == other.biz_id,
            self.biz_pbu == other.biz_pbu,
            self.cl_ord_id == other.cl_ord_id,
            self.security_id == other.security_id,
            self.ord_rej_reason == other.ord_rej_reason,
            self.trade_date == other.trade_date,
            self.transact_time == other.transact_time,
            self.user_info == other.user_info
        ])
        
    


class CancelReject(BinaryCodec):
    def __init__(self):
        self.pbu = ''
        self.set_id = 0
        self.report_index = 0
        self.biz_id = 0
        self.biz_pbu = ''
        self.cl_ord_id = ''
        self.security_id = ''
        self.orig_cl_ord_id = ''
        self.branch_id = ''
        self.cxl_rej_reason = 0
        self.trade_date = 0
        self.transact_time = 0
        self.user_info = ''
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.pbu, 8)
        buffer.write_u32(self.set_id)
        buffer.write_u64(self.report_index)
        buffer.write_u32(self.biz_id)
        write_fixed_string(buffer, self.biz_pbu, 8)
        write_fixed_string(buffer, self.cl_ord_id, 10)
        write_fixed_string(buffer, self.security_id, 12)
        write_fixed_string(buffer, self.orig_cl_ord_id, 10)
        write_fixed_string(buffer, self.branch_id, 8)
        buffer.write_u32(self.cxl_rej_reason)
        buffer.write_u32(self.trade_date)
        buffer.write_u64(self.transact_time)
        write_fixed_string(buffer, self.user_info, 32)
    
    def decode(self, buffer: ByteBuf):
        self.pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.set_id = buffer.read_u32()
        self.report_index = buffer.read_u64()
        self.biz_id = buffer.read_u32()
        self.biz_pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.security_id = buffer.read_bytes(12).decode('utf-8').strip('\x00')
        self.orig_cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.branch_id = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cxl_rej_reason = buffer.read_u32()
        self.trade_date = buffer.read_u32()
        self.transact_time = buffer.read_u64()
        self.user_info = buffer.read_bytes(32).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.pbu == other.pbu,
            self.set_id == other.set_id,
            self.report_index == other.report_index,
            self.biz_id == other.biz_id,
            self.biz_pbu == other.biz_pbu,
            self.cl_ord_id == other.cl_ord_id,
            self.security_id == other.security_id,
            self.orig_cl_ord_id == other.orig_cl_ord_id,
            self.branch_id == other.branch_id,
            self.cxl_rej_reason == other.cxl_rej_reason,
            self.trade_date == other.trade_date,
            self.transact_time == other.transact_time,
            self.user_info == other.user_info
        ])
        
    


class PlatformState(BinaryCodec):
    def __init__(self):
        self.platform_id = 0
        self.platform_state = 0
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u16(self.platform_id)
        buffer.write_u16(self.platform_state)
    
    def decode(self, buffer: ByteBuf):
        self.platform_id = buffer.read_u16()
        self.platform_state = buffer.read_u16()
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.platform_id == other.platform_id,
            self.platform_state == other.platform_state
        ])
        
    


class SubExecRptSync(BinaryCodec):
    def __init__(self):
        self.pbu = ''
        self.set_id = 0
        self.begin_report_index = 0
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.pbu, 8)
        buffer.write_u32(self.set_id)
        buffer.write_u64(self.begin_report_index)
    
    def decode(self, buffer: ByteBuf):
        self.pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.set_id = buffer.read_u32()
        self.begin_report_index = buffer.read_u64()
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.pbu == other.pbu,
            self.set_id == other.set_id,
            self.begin_report_index == other.begin_report_index
        ])
        
    
class ExecRptSync(BinaryCodec):
    def __init__(self):
        self.sub_exec_rpt_sync = []
    
    def encode(self, buffer: ByteBuf):
        size = len(self.sub_exec_rpt_sync)
        buffer.write_u16(size)
        for i in range(size):
            self.sub_exec_rpt_sync[i].encode(buffer)
        
    
    def decode(self, buffer: ByteBuf):
        size = get_len(buffer, 'u16')
        for i in range(size):
            _sub_exec_rpt_sync = SubExecRptSync()
            _sub_exec_rpt_sync.decode(buffer)
            self.sub_exec_rpt_sync.append(_sub_exec_rpt_sync)
        
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.sub_exec_rpt_sync == other.sub_exec_rpt_sync
        ])
        
    


class ExecRptEndOfStream(BinaryCodec):
    def __init__(self):
        self.pbu = ''
        self.set_id = 0
        self.end_report_index = 0
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.pbu, 8)
        buffer.write_u32(self.set_id)
        buffer.write_u64(self.end_report_index)
    
    def decode(self, buffer: ByteBuf):
        self.pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.set_id = buffer.read_u32()
        self.end_report_index = buffer.read_u64()
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.pbu == other.pbu,
            self.set_id == other.set_id,
            self.end_report_index == other.end_report_index
        ])
        
    


class SseBinary(BinaryCodec):
    def __init__(self):
        self.msg_type = 0
        self.msg_seq_num = 0
        self.msg_body_len = 0
        self.body = None
        self.checksum = 0
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u32(self.msg_type)
        buffer.write_u64(self.msg_seq_num)
        body_buf = ByteBuf()
        self.body.encode(body_buf)
        self.msg_body_len = body_buf.readable_bytes_len()
        buffer.write_u32(self.msg_body_len)
        buffer.write_bytes(body_buf.to_bytes())
        buffer.write_u32(self.checksum)
    
    def decode(self, buffer: ByteBuf):
        self.msg_type = buffer.read_u32()
        self.msg_seq_num = buffer.read_u64()
        self.msg_body_len = buffer.read_u32()
        if self.msg_type == 33:
            self.body = Heartbeat()
        if self.msg_type == 40:
            self.body = Logon()
        if self.msg_type == 41:
            self.body = Logout()
        if self.msg_type == 58:
            self.body = NewOrderSingle()
        if self.msg_type == 61:
            self.body = OrderCancel()
        if self.msg_type == 32:
            self.body = Confirm()
        if self.msg_type == 59:
            self.body = CancelReject()
        if self.msg_type == 103:
            self.body = Report()
        if self.msg_type == 204:
            self.body = OrderReject()
        if self.msg_type == 209:
            self.body = PlatformState()
        if self.msg_type == 208:
            self.body = ExecRptInfo()
        if self.msg_type == 206:
            self.body = ExecRptSync()
        if self.msg_type == 207:
            self.body = ExecRptSyncRsp()
        if self.msg_type == 210:
            self.body = ExecRptEndOfStream()
        self.body.decode(buffer)
        self.checksum = buffer.read_u32()
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.msg_type == other.msg_type,
            self.msg_seq_num == other.msg_seq_num,
            self.msg_body_len == other.msg_body_len,
            self.body == other.body,
            self.checksum == other.checksum
        ])
        
    


class Logout(BinaryCodec):
    def __init__(self):
        self.session_status = 0
        self.text = ''
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u32(self.session_status)
        write_fixed_string(buffer, self.text, 64)
    
    def decode(self, buffer: ByteBuf):
        self.session_status = buffer.read_u32()
        self.text = buffer.read_bytes(64).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.session_status == other.session_status,
            self.text == other.text
        ])
        
    


class OrderCancel(BinaryCodec):
    def __init__(self):
        self.biz_id = 0
        self.biz_pbu = ''
        self.cl_ord_id = ''
        self.security_id = ''
        self.account = ''
        self.owner_type = 0
        self.side = ''
        self.orig_cl_ord_id = ''
        self.transact_time = 0
        self.branch_id = ''
        self.user_info = ''
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u32(self.biz_id)
        write_fixed_string(buffer, self.biz_pbu, 8)
        write_fixed_string(buffer, self.cl_ord_id, 10)
        write_fixed_string(buffer, self.security_id, 12)
        write_fixed_string(buffer, self.account, 13)
        buffer.write_u8(self.owner_type)
        write_fixed_string(buffer, self.side, 1)
        write_fixed_string(buffer, self.orig_cl_ord_id, 10)
        buffer.write_u64(self.transact_time)
        write_fixed_string(buffer, self.branch_id, 8)
        write_fixed_string(buffer, self.user_info, 32)
    
    def decode(self, buffer: ByteBuf):
        self.biz_id = buffer.read_u32()
        self.biz_pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.security_id = buffer.read_bytes(12).decode('utf-8').strip('\x00')
        self.account = buffer.read_bytes(13).decode('utf-8').strip('\x00')
        self.owner_type = buffer.read_u8()
        self.side = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.orig_cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.transact_time = buffer.read_u64()
        self.branch_id = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.user_info = buffer.read_bytes(32).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.biz_id == other.biz_id,
            self.biz_pbu == other.biz_pbu,
            self.cl_ord_id == other.cl_ord_id,
            self.security_id == other.security_id,
            self.account == other.account,
            self.owner_type == other.owner_type,
            self.side == other.side,
            self.orig_cl_ord_id == other.orig_cl_ord_id,
            self.transact_time == other.transact_time,
            self.branch_id == other.branch_id,
            self.user_info == other.user_info
        ])
        
    


class SubExecRptSyncRsp(BinaryCodec):
    def __init__(self):
        self.pbu = ''
        self.set_id = 0
        self.begin_report_index = 0
        self.end_report_index = 0
        self.rej_reason = 0
        self.text = ''
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.pbu, 8)
        buffer.write_u32(self.set_id)
        buffer.write_u64(self.begin_report_index)
        buffer.write_u64(self.end_report_index)
        buffer.write_u32(self.rej_reason)
        write_fixed_string(buffer, self.text, 64)
    
    def decode(self, buffer: ByteBuf):
        self.pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.set_id = buffer.read_u32()
        self.begin_report_index = buffer.read_u64()
        self.end_report_index = buffer.read_u64()
        self.rej_reason = buffer.read_u32()
        self.text = buffer.read_bytes(64).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.pbu == other.pbu,
            self.set_id == other.set_id,
            self.begin_report_index == other.begin_report_index,
            self.end_report_index == other.end_report_index,
            self.rej_reason == other.rej_reason,
            self.text == other.text
        ])
        
    
class ExecRptSyncRsp(BinaryCodec):
    def __init__(self):
        self.sub_exec_rpt_sync_rsp = []
    
    def encode(self, buffer: ByteBuf):
        size = len(self.sub_exec_rpt_sync_rsp)
        buffer.write_u16(size)
        for i in range(size):
            self.sub_exec_rpt_sync_rsp[i].encode(buffer)
        
    
    def decode(self, buffer: ByteBuf):
        size = get_len(buffer, 'u16')
        for i in range(size):
            _sub_exec_rpt_sync_rsp = SubExecRptSyncRsp()
            _sub_exec_rpt_sync_rsp.decode(buffer)
            self.sub_exec_rpt_sync_rsp.append(_sub_exec_rpt_sync_rsp)
        
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.sub_exec_rpt_sync_rsp == other.sub_exec_rpt_sync_rsp
        ])
        
    


class Heartbeat(BinaryCodec):
    def __init__(self):
        pass
    
    def encode(self, buffer: ByteBuf):
        pass
    
    def decode(self, buffer: ByteBuf):
        pass
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return True
    


class Logon(BinaryCodec):
    def __init__(self):
        self.sender_comp_id = ''
        self.target_comp_id = ''
        self.heart_bt_int = 0
        self.prtcl_version = ''
        self.trade_date = 0
        self.q_size = 0
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.sender_comp_id, 32)
        write_fixed_string(buffer, self.target_comp_id, 32)
        buffer.write_u16(self.heart_bt_int)
        write_fixed_string(buffer, self.prtcl_version, 8)
        buffer.write_u32(self.trade_date)
        buffer.write_u32(self.q_size)
    
    def decode(self, buffer: ByteBuf):
        self.sender_comp_id = buffer.read_bytes(32).decode('utf-8').strip('\x00')
        self.target_comp_id = buffer.read_bytes(32).decode('utf-8').strip('\x00')
        self.heart_bt_int = buffer.read_u16()
        self.prtcl_version = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.trade_date = buffer.read_u32()
        self.q_size = buffer.read_u32()
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.sender_comp_id == other.sender_comp_id,
            self.target_comp_id == other.target_comp_id,
            self.heart_bt_int == other.heart_bt_int,
            self.prtcl_version == other.prtcl_version,
            self.trade_date == other.trade_date,
            self.q_size == other.q_size
        ])
        
    


class Confirm(BinaryCodec):
    def __init__(self):
        self.pbu = ''
        self.set_id = 0
        self.report_index = 0
        self.biz_id = 0
        self.exec_type = ''
        self.biz_pbu = ''
        self.cl_ord_id = ''
        self.security_id = ''
        self.account = ''
        self.owner_type = 0
        self.side = ''
        self.price = 0
        self.order_qty = 0
        self.leaves_qty = 0
        self.cxl_qty = 0
        self.ord_type = ''
        self.time_in_force = ''
        self.ord_status = ''
        self.credit_tag = ''
        self.orig_cl_ord_id = ''
        self.clearing_firm = ''
        self.branch_id = ''
        self.ord_rej_reason = 0
        self.ord_cnfm_id = ''
        self.orig_ord_cnfm_id = ''
        self.trade_date = 0
        self.transact_time = 0
        self.user_info = ''
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.pbu, 8)
        buffer.write_u32(self.set_id)
        buffer.write_u64(self.report_index)
        buffer.write_u32(self.biz_id)
        write_fixed_string(buffer, self.exec_type, 1)
        write_fixed_string(buffer, self.biz_pbu, 8)
        write_fixed_string(buffer, self.cl_ord_id, 10)
        write_fixed_string(buffer, self.security_id, 12)
        write_fixed_string(buffer, self.account, 13)
        buffer.write_u8(self.owner_type)
        write_fixed_string(buffer, self.side, 1)
        buffer.write_i64(self.price)
        buffer.write_i64(self.order_qty)
        buffer.write_i64(self.leaves_qty)
        buffer.write_i64(self.cxl_qty)
        write_fixed_string(buffer, self.ord_type, 1)
        write_fixed_string(buffer, self.time_in_force, 1)
        write_fixed_string(buffer, self.ord_status, 1)
        write_fixed_string(buffer, self.credit_tag, 2)
        write_fixed_string(buffer, self.orig_cl_ord_id, 10)
        write_fixed_string(buffer, self.clearing_firm, 8)
        write_fixed_string(buffer, self.branch_id, 8)
        buffer.write_u32(self.ord_rej_reason)
        write_fixed_string(buffer, self.ord_cnfm_id, 16)
        write_fixed_string(buffer, self.orig_ord_cnfm_id, 16)
        buffer.write_u32(self.trade_date)
        buffer.write_u64(self.transact_time)
        write_fixed_string(buffer, self.user_info, 32)
    
    def decode(self, buffer: ByteBuf):
        self.pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.set_id = buffer.read_u32()
        self.report_index = buffer.read_u64()
        self.biz_id = buffer.read_u32()
        self.exec_type = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.biz_pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.security_id = buffer.read_bytes(12).decode('utf-8').strip('\x00')
        self.account = buffer.read_bytes(13).decode('utf-8').strip('\x00')
        self.owner_type = buffer.read_u8()
        self.side = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.price = buffer.read_i64()
        self.order_qty = buffer.read_i64()
        self.leaves_qty = buffer.read_i64()
        self.cxl_qty = buffer.read_i64()
        self.ord_type = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.time_in_force = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.ord_status = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.credit_tag = buffer.read_bytes(2).decode('utf-8').strip('\x00')
        self.orig_cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.clearing_firm = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.branch_id = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.ord_rej_reason = buffer.read_u32()
        self.ord_cnfm_id = buffer.read_bytes(16).decode('utf-8').strip('\x00')
        self.orig_ord_cnfm_id = buffer.read_bytes(16).decode('utf-8').strip('\x00')
        self.trade_date = buffer.read_u32()
        self.transact_time = buffer.read_u64()
        self.user_info = buffer.read_bytes(32).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.pbu == other.pbu,
            self.set_id == other.set_id,
            self.report_index == other.report_index,
            self.biz_id == other.biz_id,
            self.exec_type == other.exec_type,
            self.biz_pbu == other.biz_pbu,
            self.cl_ord_id == other.cl_ord_id,
            self.security_id == other.security_id,
            self.account == other.account,
            self.owner_type == other.owner_type,
            self.side == other.side,
            self.price == other.price,
            self.order_qty == other.order_qty,
            self.leaves_qty == other.leaves_qty,
            self.cxl_qty == other.cxl_qty,
            self.ord_type == other.ord_type,
            self.time_in_force == other.time_in_force,
            self.ord_status == other.ord_status,
            self.credit_tag == other.credit_tag,
            self.orig_cl_ord_id == other.orig_cl_ord_id,
            self.clearing_firm == other.clearing_firm,
            self.branch_id == other.branch_id,
            self.ord_rej_reason == other.ord_rej_reason,
            self.ord_cnfm_id == other.ord_cnfm_id,
            self.orig_ord_cnfm_id == other.orig_ord_cnfm_id,
            self.trade_date == other.trade_date,
            self.transact_time == other.transact_time,
            self.user_info == other.user_info
        ])
        
    


class Report(BinaryCodec):
    def __init__(self):
        self.pbu = ''
        self.set_id = 0
        self.report_index = 0
        self.biz_id = 0
        self.exec_type = ''
        self.biz_pbu = ''
        self.cl_ord_id = ''
        self.security_id = ''
        self.account = ''
        self.owner_type = 0
        self.side = ''
        self.price = 0
        self.order_qty = 0
        self.leaves_qty = 0
        self.cxl_qty = 0
        self.ord_type = ''
        self.time_in_force = ''
        self.ord_status = ''
        self.credit_tag = ''
        self.orig_cl_ord_id = ''
        self.clearing_firm = ''
        self.branch_id = ''
        self.ord_rej_reason = 0
        self.ord_cnfm_id = ''
        self.orig_ord_cnfm_id = ''
        self.trade_date = 0
        self.transact_time = 0
        self.user_info = ''
    
    def encode(self, buffer: ByteBuf):
        write_fixed_string(buffer, self.pbu, 8)
        buffer.write_u32(self.set_id)
        buffer.write_u64(self.report_index)
        buffer.write_u32(self.biz_id)
        write_fixed_string(buffer, self.exec_type, 1)
        write_fixed_string(buffer, self.biz_pbu, 8)
        write_fixed_string(buffer, self.cl_ord_id, 10)
        write_fixed_string(buffer, self.security_id, 12)
        write_fixed_string(buffer, self.account, 13)
        buffer.write_u8(self.owner_type)
        write_fixed_string(buffer, self.side, 1)
        buffer.write_i64(self.price)
        buffer.write_i64(self.order_qty)
        buffer.write_i64(self.leaves_qty)
        buffer.write_i64(self.cxl_qty)
        write_fixed_string(buffer, self.ord_type, 1)
        write_fixed_string(buffer, self.time_in_force, 1)
        write_fixed_string(buffer, self.ord_status, 1)
        write_fixed_string(buffer, self.credit_tag, 2)
        write_fixed_string(buffer, self.orig_cl_ord_id, 10)
        write_fixed_string(buffer, self.clearing_firm, 8)
        write_fixed_string(buffer, self.branch_id, 8)
        buffer.write_u32(self.ord_rej_reason)
        write_fixed_string(buffer, self.ord_cnfm_id, 16)
        write_fixed_string(buffer, self.orig_ord_cnfm_id, 16)
        buffer.write_u32(self.trade_date)
        buffer.write_u64(self.transact_time)
        write_fixed_string(buffer, self.user_info, 32)
    
    def decode(self, buffer: ByteBuf):
        self.pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.set_id = buffer.read_u32()
        self.report_index = buffer.read_u64()
        self.biz_id = buffer.read_u32()
        self.exec_type = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.biz_pbu = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.security_id = buffer.read_bytes(12).decode('utf-8').strip('\x00')
        self.account = buffer.read_bytes(13).decode('utf-8').strip('\x00')
        self.owner_type = buffer.read_u8()
        self.side = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.price = buffer.read_i64()
        self.order_qty = buffer.read_i64()
        self.leaves_qty = buffer.read_i64()
        self.cxl_qty = buffer.read_i64()
        self.ord_type = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.time_in_force = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.ord_status = buffer.read_bytes(1).decode('utf-8').strip('\x00')
        self.credit_tag = buffer.read_bytes(2).decode('utf-8').strip('\x00')
        self.orig_cl_ord_id = buffer.read_bytes(10).decode('utf-8').strip('\x00')
        self.clearing_firm = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.branch_id = buffer.read_bytes(8).decode('utf-8').strip('\x00')
        self.ord_rej_reason = buffer.read_u32()
        self.ord_cnfm_id = buffer.read_bytes(16).decode('utf-8').strip('\x00')
        self.orig_ord_cnfm_id = buffer.read_bytes(16).decode('utf-8').strip('\x00')
        self.trade_date = buffer.read_u32()
        self.transact_time = buffer.read_u64()
        self.user_info = buffer.read_bytes(32).decode('utf-8').strip('\x00')
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.pbu == other.pbu,
            self.set_id == other.set_id,
            self.report_index == other.report_index,
            self.biz_id == other.biz_id,
            self.exec_type == other.exec_type,
            self.biz_pbu == other.biz_pbu,
            self.cl_ord_id == other.cl_ord_id,
            self.security_id == other.security_id,
            self.account == other.account,
            self.owner_type == other.owner_type,
            self.side == other.side,
            self.price == other.price,
            self.order_qty == other.order_qty,
            self.leaves_qty == other.leaves_qty,
            self.cxl_qty == other.cxl_qty,
            self.ord_type == other.ord_type,
            self.time_in_force == other.time_in_force,
            self.ord_status == other.ord_status,
            self.credit_tag == other.credit_tag,
            self.orig_cl_ord_id == other.orig_cl_ord_id,
            self.clearing_firm == other.clearing_firm,
            self.branch_id == other.branch_id,
            self.ord_rej_reason == other.ord_rej_reason,
            self.ord_cnfm_id == other.ord_cnfm_id,
            self.orig_ord_cnfm_id == other.orig_ord_cnfm_id,
            self.trade_date == other.trade_date,
            self.transact_time == other.transact_time,
            self.user_info == other.user_info
        ])
        
    


class ExecRptInfo(BinaryCodec):
    def __init__(self):
        self.platform_id = 0
        self.pbu = []
        self.set_id = []
    
    def encode(self, buffer: ByteBuf):
        buffer.write_u16(self.platform_id)
        size = len(self.pbu)
        buffer.write_u16(size)
        for i in range(size):
            write_fixed_string(buffer, self.pbu[i], 8)
        
        size = len(self.set_id)
        buffer.write_u16(size)
        for i in range(size):
            buffer.write_u32(self.set_id[i])
        
    
    def decode(self, buffer: ByteBuf):
        self.platform_id = buffer.read_u16()
        size = get_len(buffer, 'u16')
        for i in range(size):
            self.pbu.append(buffer.read_bytes(8).decode('utf-8').strip('\x00'))
        
        size = get_len(buffer, 'u16')
        for i in range(size):
            self.set_id.append(buffer.read_u32())
        
    
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            return False
        return all([
            self.platform_id == other.platform_id,
            self.pbu == other.pbu,
            self.set_id == other.set_id
        ])
        
    


