# Code generated by fin-protoc. DO NOT EDIT.
import unittest

from sse_binary import *

class TestSseBinaryNotGen(unittest.TestCase):
    def setUp(self):
        body = Logon()
        body.sender_comp_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        body.target_comp_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        body.heart_bt_int = 2
        body.prtcl_version = "xxxxxxxx"
        body.trade_date = 4
        body.q_size = 4
        
        self.packet = SseBinary()
        self.packet.msg_seq_num = 8
        self.packet.msg_body_len = 4
        self.packet.msg_type = 40
        self.packet.body = body
        self.packet.checksum = 4
        

    def test_encode_decode(self):
        buf = ByteBuf()
        self.packet.encode(buf)
        decoded_packet = SseBinary()
        decoded_packet.decode(buf)
        self.assertEqual(decoded_packet, self.packet)




if __name__ == '__main__':
    unittest.main()
